<script>
	require([
		"jquery",
		"Magento_Ui/js/modal/modal"
	], function($, modal){
		var options = {
			type: 'popup',
			responsive: true,
			innerScroll: true,
			title: "Select store from the Dropdown", //write your popup title 
			
		};
		var popupdata = $('<div />').append($('#custom-model-popup'));
		modal(options, popupdata);
		popupdata.modal('openModal');
	});
</script>



<div class="mine" id="custom-model-popup">
<style>

.dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}


.dropdown {
  position: relative;
  display: inline-block;
}


.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}


.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}


.dropdown-content a:hover {background-color: #ddd;}


.dropdown:hover .dropdown-content {display: block;}


.dropdown:hover .dropbtn {background-color: #3e8e41;}

.mine {
  height: 200px;
  width: 50%;
}
</style>


<div class="dropdown">

<button class="dropbtn">
<?php if (count($block->getGroups())>1): ?>
<?= $block->escapeHtml(__('Select Store')) ?></<button>
        <div class="dropdown-content">
        <?php foreach ($block->getGroups() as $_group): ?>
	<?php if ($_group->getId() == $block->getCurrentGroupId()): ?>
             </div>
	<div class="dropdown-content">  
	<?= $block->escapeHtml($_group->getName()) ?>
	<?php endif; ?>
	<?php endforeach; ?>
		<?php foreach ($block->getGroups() as $_group): ?>
		<?php if (!($_group->getId() == $block->getCurrentGroupId())): ?>
        		<a href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_group->getDefaultStore()) ?>'>
	<?= $block->escapeHtml($_group->getName()) ?></a>
               
		<?php endif; ?>
		<?php endforeach; ?></div>
      
<?php endif; ?>

</div>
